const XLSX = require('xlsx');

/**
 * Sanitize schema fields by filling empty names and de-duplicating names (TC-10, TC-11)
 */
function sanitizeSchemaFields(fields) {
  if (!fields || !Array.isArray(fields) || fields.length === 0) return [];
  const seen = {};
  return fields.map((f, idx) => {
    let name = (f && f.name ? String(f.name) : '').trim();
    if (!name) {
      name = `field_${idx + 1}`;
    }
    name = name.replace(/[^a-zA-Z0-9_]/g, '_');
    if (!name) name = `col_${idx + 1}`;

    let uniqueName = name;
    if (seen[name]) {
      seen[name]++;
      uniqueName = `${name}_${seen[name]}`;
    } else {
      seen[name] = 1;
    }

    return {
      ...(typeof f === 'object' ? f : {}),
      name: uniqueName
    };
  });
}

/**
 * Escape a value for CSV with Formula Injection mitigation (TC-13)
 */
function escapeCSVValue(val, delimiter = ',') {
  if (val === null || val === undefined) return '';
  let str = String(val);

  // CSV Formula Injection mitigation:
  if (/^[=+\-@\t\r|]/.test(str)) {
    str = "'" + str;
  }

  if (str.includes(delimiter) || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Format records to CSV string
 */
function toCSV(records, fields, options = {}) {
  const sanitized = sanitizeSchemaFields(fields);
  const fieldNames = sanitized.map(f => f.name);

  if (!fieldNames.length) return '';

  const delimiter = options.delimiter || ',';
  const includeHeader = options.header !== false && options.header !== 'false';
  const includeBOM = options.bom === true || options.bom === 'true';

  const lines = [];

  if (includeBOM) {
    lines.push('\uFEFF');
  }

  if (includeHeader) {
    lines.push(fieldNames.map(f => escapeCSVValue(f, delimiter)).join(delimiter));
  }

  if (Array.isArray(records)) {
    for (const row of records) {
      if (!row) continue;
      const line = fieldNames.map(name => escapeCSVValue(row[name], delimiter)).join(delimiter);
      lines.push(line);
    }
  }

  return lines.join(options.lineEnding === 'crlf' ? '\r\n' : '\n');
}

/**
 * Format records to JSON string
 */
function toJSON(records, options = {}) {
  const pretty = options.minify !== true && options.minify !== 'true';
  return JSON.stringify(records || [], null, pretty ? 2 : 0);
}

/**
 * Escape a value for SQL
 */
function escapeSQLValue(val, dialect = 'postgres') {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return isNaN(val) ? 'NULL' : String(val);
  if (typeof val === 'boolean') {
    if (dialect === 'sqlite') return val ? '1' : '0';
    return val ? 'TRUE' : 'FALSE';
  }
  return `'${String(val).replace(/'/g, "''")}'`;
}

/**
 * Escape and sanitize SQL identifier
 */
function escapeIdentifier(id, dialect = 'postgres') {
  const safe = String(id || 'mock_data').replace(/[^a-zA-Z0-9_]/g, '_');
  if (dialect === 'mysql') return `\`${safe}\``;
  return `"${safe}"`;
}

/**
 * Format records to SQL INSERT statements
 */
function toSQL(records, fields, options = {}) {
  const sanitized = sanitizeSchemaFields(fields);
  const fieldNames = sanitized.map(f => f.name);

  if (!records || !records.length || !fieldNames.length) {
    return '-- No data or columns specified for SQL export';
  }

  const rawTableName = options.tableName || 'mock_data';
  const dialect = (options.dialect || 'postgres').toLowerCase();

  const escapedTable = escapeIdentifier(rawTableName, dialect);
  const escapedCols = fieldNames.map(f => escapeIdentifier(f, dialect)).join(', ');

  const statements = [];
  statements.push(`-- SQL Export generated by Mockaroo Local`);
  statements.push(`-- Dialect: ${dialect.toUpperCase()} | Table: ${escapedTable} | Records: ${records.length}\n`);

  const batchSize = 100;
  for (let i = 0; i < records.length; i += batchSize) {
    const chunk = records.slice(i, i + batchSize);
    const valueRows = chunk.map(row => {
      const vals = fieldNames.map(col => escapeSQLValue(row[col], dialect)).join(', ');
      return `  (${vals})`;
    });

    statements.push(`INSERT INTO ${escapedTable} (${escapedCols})\nVALUES\n${valueRows.join(',\n')};`);
  }

  return statements.join('\n\n');
}

/**
 * Format records to Excel buffer (.xlsx)
 */
function toExcel(records, fields) {
  const sanitized = sanitizeSchemaFields(fields);
  const fieldNames = sanitized.map(f => f.name);

  if (!fieldNames.length) {
    throw new Error('No columns defined for Excel generation.');
  }

  const safeRecords = Array.isArray(records) ? records : [];
  const cleanData = safeRecords.map(row => {
    const obj = {};
    for (const name of fieldNames) {
      obj[name] = row ? (row[name] ?? '') : '';
    }
    return obj;
  });

  const worksheet = XLSX.utils.json_to_sheet(cleanData, { header: fieldNames });

  const colWidths = fieldNames.map(name => {
    let maxLen = name.length;
    for (const r of cleanData.slice(0, 100)) {
      const len = String(r[name] || '').length;
      if (len > maxLen) maxLen = len;
    }
    return { wch: Math.min(Math.max(maxLen + 3, 10), 40) };
  });
  worksheet['!cols'] = colWidths;

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Data');

  return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' });
}

module.exports = {
  sanitizeSchemaFields,
  toCSV,
  toJSON,
  toSQL,
  toExcel
};
